//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrol_Lawn_Care.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_CLCEntities : DbContext
    {
        public DB_CLCEntities()
            : base("name=DB_CLCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblCust> TblCusts { get; set; }
        public virtual DbSet<TblEmp> TblEmps { get; set; }
        public virtual DbSet<TblEquip> TblEquips { get; set; }
        public virtual DbSet<TblMaintRec> TblMaintRecs { get; set; }
        public virtual DbSet<TblPer> TblPers { get; set; }
        public virtual DbSet<TblProp> TblProps { get; set; }
        public virtual DbSet<TblTool> TblTools { get; set; }
        public virtual DbSet<TblVehicle> TblVehicles { get; set; }
    }
}
