//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrol_Lawn_Care.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_CLCEntities : DbContext
    {
        public DB_CLCEntities()
            : base("name=DB_CLCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<AssignedEmp> AssignedEmps { get; set; }
        public virtual DbSet<Equip> Equips { get; set; }
        public virtual DbSet<MaintenanceRecord> MaintenanceRecords { get; set; }
        public virtual DbSet<Manage> Manages { get; set; }
        public virtual DbSet<Owns> Owns { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Prop> Props { get; set; }
        public virtual DbSet<Tool> Tools { get; set; }
        public virtual DbSet<AssignedTool> AssignedTools { get; set; }
        public virtual DbSet<AssignedTruck> AssignedTrucks { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
    }
}
