//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrol_Lawn_Care.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblEmp
    {
        public int empId { get; set; }
        public int perId { get; set; }
        public float payRate { get; set; }
        public int ssn { get; set; }
        public int managedBy { get; set; }
    
        public virtual TblPer TblPer { get; set; }
        public virtual TblPer TblPer1 { get; set; }
    }
}
