//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Carrol_Lawn_Care.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblProp()
        {
            this.TblPers = new HashSet<TblPer>();
        }
    
        public int propId { get; set; }
        public string address { get; set; }
        public string services { get; set; }
        public float cost { get; set; }
        public string recurrence { get; set; }
        public Nullable<int> perId { get; set; }
        public Nullable<int> equipId { get; set; }
    
        public virtual TblEquip TblEquip { get; set; }
        public virtual TblPer TblPer { get; set; }
        public virtual TblEquip TblEquip1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblPer> TblPers { get; set; }
    }
}
